#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Coder In Training

author: Phillip Green II

# Short bio or description (displayed in the header)
description: A collection of my solutions to programming problems I have come across.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://secure.gravatar.com/avatar/afd80bfa42d7b546eecd38e7601e4be2.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: phillipgreenii
  instagram:
  linkedin: phillipgreenii
  pinterest:
  rss: true
  twitter: deafcheese
  stackoverflow: users/388006/pgreen2


disqus: phillipgreenii

google_analytics: UA-57611647-1

url: http://phillipgreenii.github.io

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
